from django.urls import path
from .views import *


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('portfolio/visual-identity-and-graphic-design', LogoArchive.as_view(), name='logo-design-archive'),
    path('portfolio/business-and-brand-identity', DigitalArchive.as_view(), name='digital-branding'),
    path('portfolio/motion-design', MotionDesignArchive.as_view(), name='motion-design'),
    path('portfolio/photgraphy-and-videography', AdvertisingPhotoArchive.as_view(), name='photgraphy-and-videography'),
    path('portfolio/campaign', IllustrationArchive.as_view(), name='campaign'),
    path('portfolio/gamification', GameDesignArchive.as_view(), name='gamification'),
    path('portfolio/video-making', VideoMakingArchive.as_view(), name='video-making'),
    path('portfolio/detail', PortfolioDetailSample.as_view(), name='portfolio-detail'),
    path('portfolio/viana/detail', PortfolioVianaDetail.as_view(), name='portfolio-viana'),
    path('portfolio/zelmond/detail', PortfolioZelmondDetail.as_view(), name='portfolio-zelmond'),
    path('portfolio/lucano/detail', PortfolioLucanoDetail.as_view(), name='portfolio-lucano'),
    path('portfolio/navar/detail', PortfolioNavarDetail.as_view(), name='portfolio-navar'),
    path('portfolio/netent-poker/detail', PortfolioNetentPokerDetail.as_view(), name='portfolio-netentpoker'),
    path('portfolio/breaking-muscle/detail', PortfolioBreakingMuscleDetail.as_view(), name='portfolio-breaking-muscle'),
    path('portfolio/dyarino/detail', PortfolioDyarinoDetail.as_view(), name='portfolio-dyarino'),
    path('portfolio/ghabile/detail', PortfolioGhabileDetail.as_view(), name='portfolio-ghabile'),
    path('portfolio/hayloo/detail', PortfolioHaylooDetail.as_view(), name='portfolio-hayloo'),
    path('portfolio/sbt/detail', PortfolioSBTDetail.as_view(), name='portfolio-sbt'),
    path('portfolio/ariobarzan/detail', PortfolioAriobarzanDetail.as_view(), name='portfolio-ario'),
    path('portfolio/talashim/detail', PortfolioTalashimDetail.as_view(), name='portfolio-talashim'),
    path('portfolio/kunzite/detail', PortfolioKunziteDetail.as_view(), name='portfolio-kunzite'),
    path('portfolio/regenbogen/detail', PortfolioRegenbogenDetail.as_view(), name='portfolio-regenbogen'),
    path('portfolio/modernkey/detail', PortfolioModernKeyDetail.as_view(), name='portfolio-modernkey'),
    path('portfolio/inanlou-showroom/detail', PortfolioInanlooDetail.as_view(), name='portfolio-inanlou'),
    path('portfolio/negah-holding/detail', PortfolioNegahDetail.as_view(), name='portfolio-negah'),
    path('portfolio/negahban-mammut/detail', PortfolioNegahbanmamutDetail.as_view(), name='portfolio-negahban-mammut'),
    path('portfolio/bunny-mode/detail', PortfolioBunnyModeDetail.as_view(), name='portfolio-bunny-mode'),
    path('portfolio/azki/detail', PortfolioAzkiDetail.as_view(), name='portfolio-azki'),
    path('portfolio/monji/detail', PortfolioMonjiDetail.as_view(), name='portfolio-monji'),
    path('portfolio/kanirush/detail', PortfolioKanirushDetail.as_view(), name='portfolio-kanirush'),
    path('portfolio/cheragh-bargh/detail', PortfolioCheraghBarghDetail.as_view(), name='portfolio-cheraghbargh'),
    path('portfolio/mammut-vip-tour/detail', PortfolioMammutVIPTourDetail.as_view(), name='portfolio-mammut-vip-tour'),
]